### ISSUE TITLE
the use of video faceswap

### ISSUE THREAD

**Issue by corlangerak** [uelordi01/mediapipe_faceswap#1]
would it be possible to use a video of a face to swap with, instead of an image?
I am not really experienced yet..
Tried to upload a video file in the:
`change_face_list = []`

 But that doesn't work

any ideas on how to implement this?

**Comment by uelordi01** [comment]
Hi, @corlangerak :

This repository takes an input image with landmarks, creates triangles to swap into a video. 
I think your idea is possible to implement using this code, but it is not the objective of this repo. 
 
Anyway, I think it is relatively easy to change this feature. 
Instead of using imread to load the image, you can use another video capture object grab the frame, and use this to take the triangles for the target video - or camera. 

So, in few words. 


pseudocode: 

input_video =  cv2.VideoCapture("your_input_video")

```
while cap.isOpened():
        success, webcam_img = cap.read()
        input_video_mat = input_video.read() # your input video video capture Mat
        if not success:
            break
        if flag_change_face:
            base_face_handler, landmark_base_ocv, base_input_image = \
                process_base_face_mesh(drawing_spec, face_mesh,input_video_mat , # the matrix of the image
                                       show_landmarks=key_draw_landmarks,
                                       show_triangulated_mesh=key_draw_landmarks)

You will also need to make some changes in the process_base_face_mesh function. 
```
                                       
                                       
Cheers.
