### ISSUE TITLE
Face change processing

### ISSUE THREAD

**Issue by tjasmin111** [uelordi01/mediapipe_faceswap#4]
Very interesting project! Instead of face swap, is it possible to make a change on the face, like to make the nose smaller? How can we do that?

**Comment by uelordi01** [comment]
Hi, @tjasmin111 thank you for the patience. 
The short answer is no unfortunately. Because the face extraction is made by triangulation warping. In other words, I take a photograph using a face landmarks and I divide in different triangles, and then, I swap the origin face in the target face, calculating this triangle deformation. You could use face landmark information to modify the face part without swapping but I think you would need to use other computer vision techniques for filling the pixel gap if you move any face part. 

Probably, what you are finding is oriented to stylegan and generative/diffusion LoRA networks. 

Regards.
